// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghhtevedrpxenjaqqkhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoaHRldmVkcnB4ZW5qYXFxa2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODU3MTIsImV4cCI6MjA2MTM2MTcxMn0.IDb8UJvXqV22ZaAP38MCexI4OpwzRyIpA0SgftYxKhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);